#!/usr/bin/env bash

export EDITOR=vim
export BROWSER="google-chrome-stable"
export FILE="ranger"
export TERMINAL="gnome-terminal"

export NOTES_DIR="$HOME/Dropbox/1 Notes"

if [ -x /usr/bin/dircolors ]; then
  alias ls='ls --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

if [ "$(uname)" != "Darwin" ]; then
  alias open='xdg-open'
fi

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias -- -='cd -'

alias g='git'

alias ctag="`brew --prefix`/bin/ctags"

alias dnotes="cd ${NOTES_DIR}"
alias dwork="cd ~/Dropbox/0\ BSc_UW"
