#!/bin/sh
# Created by Luke Smith
[ -z "$1" ] && echo "Give a pdf file or a DOI." && exit 1

if [ -f "$1" ]; then
  doi=$(pdfinfo "$1" | grep -io "doi:.*") ||
    doi=$(pdftotext "$1" 2>/dev/null - | grep -io "doi:.*" -m 1) ||
    exit 1
else
  doi="$1"
fi

# Check crossref.org for the bib citation
curl -s "http://api.crossref.org/works/$doi/transform/application/x-bibtex" -w "\\n"
