#!/usr/bin/env bash

{
  echo -n 'export const Pywal = '
  cat "$HOME/.cache/wal/colors-speedcrunch.json"
  echo ';'
} > $HOME/Library/ApplicationSupport/Übersicht/widgets/simple-bar/lib/styles/Pywal.js
