#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Usage: $0 [path/to/image] [image_name (if none choose random)]"
  exit 1
else
  if [ -z "$2" ]; then
    ls $1 | sort -R | tail -R | while read file; do
      wal -q -i $1/$file
    done
  else
    wal -q -i $1/$2
  fi
fi

brew services restart skhd
brew services restart yabai

$HOME/scripts/setUbersichtTheme
