#!/bin/sh

session="work"

tmux start-server 
tmux new-session -d -s $session -n vim

tmux selectp -t 0
tmux send-keys "cd ~" C-m

tmux splitw -h -p 50
tmux send-keys "htop" C-m

tmux selectp -t 1
tmux splitw -v -p 70
tmux send-keys "ranger" C-m

tmux selectp -t 2
tmux splitw -v -p 50
tmux send-keys "cd ~/dotfiles" C-m

tmux selectp -t 0

tmux select-window -t $session:0

tmux attach-session -t $session
